import React from 'react'
import img from '../../assets/img/The_Bookery_Crediton.jpg'

const About = () => {
  return (
    <div className='about py-5'>
        <div className="container d-flex flex-column align-items-center">
            <img src={img} style={{"width":"35rem"}}/>
            <h1 className='mt-5'>About Us</h1>
            <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Provident eos vitae id aliquam recusandae quisquam modi ex voluptate praesentium sequi eaque hic qui nihil esse facere iure laborum doloribus cumque veniam ea porro, placeat quaerat perferendis dicta. Asperiores maxime commodi soluta atque earum nesciunt alias nemo incidunt reiciendis possimus nobis deserunt distinctio laudantium veritatis quo ex libero adipisci repudiandae beatae excepturi corporis, quas provident? Cumque iste earum magnam, odit illo commodi cupiditate sunt iusto nam quas aspernatur a inventore quis eaque ducimus modi perspiciatis aliquam. Accusamus possimus commodi inventore nostrum quaerat natus dolore dicta facere sit et culpa quibusdam vel, mollitia nesciunt explicabo porro numquam libero tempora doloribus quam optio asperiores voluptas recusandae? Eaque esse quam excepturi vero itaque. Doloribus quibusdam minima ipsa impedit repellat iste libero eveniet quidem hic! At nemo hic dicta deserunt rem? Quod itaque accusamus in, provident, odio perferendis dignissimos asperiores libero repellat iste unde accusantium omnis dicta quia ducimus deserunt alias. Inventore dolor ullam aperiam quam magni aliquid illo quaerat eum dolores. Vero quidem sit a veritatis odio delectus adipisci deleniti! Animi dicta aliquam itaque harum reiciendis inventore quam nemo ab nobis id maxime ullam, incidunt debitis dolorum officia ad at vitae fuga repellendus doloremque.</p>
            <p className='mb-5'>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Eligendi ea vero saepe iure optio error quae consectetur debitis! Placeat nostrum, eveniet veniam voluptatibus eius voluptatem eum laboriosam! Quidem non velit voluptate dignissimos labore perspiciatis amet molestiae itaque optio aperiam, animi dolor suscipit ipsa error repellendus voluptatum, officiis reiciendis a repudiandae veniam! Asperiores ipsum quia voluptatem, corporis optio omnis ut debitis placeat quasi! Incidunt totam eligendi porro, saepe aliquid dignissimos commodi ipsum architecto itaque quae asperiores sit officiis tempore reiciendis quisquam. Eligendi omnis aspernatur earum quae eaque blanditiis quisquam a corrupti laboriosam hic non maiores aliquid necessitatibus porro, incidunt totam cupiditate suscipit voluptatibus, rem et repellendus ea! Aut voluptatum inventore rerum dolorem laborum culpa odit velit consequatur aspernatur temporibus minima dolor, exercitationem natus non fuga quae sit eum repudiandae officiis ratione impedit eveniet, vel odio! Rem ex dignissimos ad, harum distinctio totam soluta! Quas totam accusamus debitis? Nesciunt quod aliquam quo vel optio culpa minus, nobis cum consectetur doloribus quos tenetur eum ullam quidem assumenda dignissimos iste voluptate natus ipsum unde? Esse, corporis fugiat! Placeat iure quam vel provident quod qui vero ea inventore obcaecati reiciendis ullam veniam assumenda odit libero est officia facilis enim, voluptatibus cumque dolorum accusamus quidem tempora debitis possimus. Asperiores minus explicabo amet sapiente perspiciatis odit reiciendis labore tempora vero impedit quo in fuga sed, odio libero voluptates a recusandae fugiat aspernatur quod, dolores adipisci aperiam enim. Molestiae delectus cum quibusdam numquam? Quam pariatur neque adipisci delectus, in at eligendi fugiat omnis minima quis voluptatum sint aspernatur consequatur animi. Odio, non mollitia iusto placeat, provident excepturi repudiandae amet consequuntur ullam nihil culpa! Neque, provident odio laudantium dolorem a odit dolorum quisquam excepturi quidem assumenda cum totam animi quis error modi corporis quibusdam deserunt hic illum accusamus natus. Voluptatibus suscipit ex nemo architecto assumenda nisi amet, nulla corporis!</p>
        </div>
    </div>
  )
}

export default About